name: Deploy to phila-wp-plugins
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build files
    runs-on: ubuntu-latest
    steps:
      - name: Bump release version
        id: bump_version
        uses: christian-draeger/increment-semantic-version@1.0.2
        with:
          current-version: '3.1.12'
          version-fragment: 'bug'
      - uses: actions/checkout@master
      - name: zip file
        uses: thedoctor0/zip-release@master
        with:
          filename: "wp-nested-pages-phila-${{ steps.bump_version.outputs.next-version }}.zip"
          exclusions: '*.git*'
      - name: Deploy to s3
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'
        run: 
          aws s3 cp wp-nested-pages-phila-${{ steps.bump_version.outputs.next-version }}.zip s3://phila-wp-plugins/wp-nested-pages-phila-${{ steps.bump_version.outputs.next-version }}.zip
